name: Update total level channel

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests beautifulsoup4

      - run: |
          for i in $(seq 1 12); do
            python update_total_level.py
            sleep 290
          done
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_XP_CHANNEL_ID: "1551663314235433070"
          DISCORD_RANK_CHANNEL_ID: "1551666092634669136"
          GROUP_NAME: "Kevs Angels"
          PLAYER_NAMES: "GIM Old Marc,GIM KevZMan,GokuMango, GIM Old Joyu, GIM Mystikz"
          NAME_TEMPLATE: "📊┃Total Level: {total:,}"
          XP_TEMPLATE: "📊┃Total XP: {xp:,}"
          RANK_TEMPLATE: "📊┃GIM Rank: #{rank:,}"
